services:
  claude-code:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}:${PWD}
      - ${HOME}/.config/gcloud:${HOME}/.config/gcloud:ro
      - ${HOME}/.config/anthropic:${HOME}/.config/anthropic:ro
      - ${HOME}/.claude:${HOME}/.claude
    environment:
      - PUID=${PUID:-$(id -u)}
      - PGID=${PGID:-$(id -g)}
      - CONTAINER_USER=${CONTAINER_USER:-user}
      - CONTAINER_GROUP=${CONTAINER_GROUP:-user}
      - GOOGLE_APPLICATION_CREDENTIALS=/home/${CONTAINER_USER:-user}/.config/gcloud/application_default_credentials.json
      - CLAUDE_CODE_USE_VERTEX=${CLAUDE_CODE_USE_VERTEX}
      - CLOUD_ML_REGION=${CLOUD_ML_REGION}
      - ANTHROPIC_VERTEX_PROJECT_ID=${ANTHROPIC_VERTEX_PROJECT_ID}
